version: '3.2'
services:
  ubuntu:
    build:
      context: ./
    tty: true
    ports:
      - "8086:80"
    volumes:
        - "./www/html:/var/www/html"

      # - "./nginx/default.conf:/etc/nginx/sites-available/default"
      # - "./radius/sql:/etc/freeradius/3.0/mods-available/sql"
      # - "./radius/default:/etc/freeradius/3.0/sites-available/default"
      # - "./radius/clients.conf:/etc/freeradius/3.0/clients.conf"
      # - "./configsFile/configg.sh:/home/"
      # - "./mysql/dbconfig.sh:/home/"

